version: "3.2"
services:
  provider:
    # image: ghcr.io/chriamue/bert-cli/bert-web:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./Rocket.toml:/Rocket.toml
